...@envs

create: {
  class: square
  perspective.class: square
  plugins.class: square
  core.class: square

  (core -> perspective).class: direct stroke
  (core -> plugins).class: direct stroke
}
third party libraries.class: square
(third party libraries -> create.perspective).class: seg stroke
(third party libraries -> create.plugins).class: seg stroke

app.class: square

(create.perspective -> app).class: direct stroke
(create.plugins -> app).class: direct stroke
