...@envs

create: {
  class: square
  perspective.class: square
  plugins.class: square
  core.class: square

  (core -> perspective).class: direct stroke
  (core -> plugins).class: direct stroke
}
third party libraries.class: square
(third party libraries -> create.perspective).class: direct stroke
(third party libraries -> create.plugins).class: direct stroke
