style: {
  fill: transparent
}

vars

classes: {
  square: {
    style: {
      stroke: purple
      stroke-width: 5
      shadow: true
    }
  }
  seg stroke: {
    style.animated: true
    style.stroke: orange
  }
  direct stroke: {
    style.stroke: "#53C0D8"
  }
}
