...@envs

petition route: {
  class: square
  request.class: square
  f.class: square
  bodyInit.class: square
  response.class: square
  headings.class: square
  return.class: square

  (headings -> f).class: direct stroke
  (f -> bodyInit).class: seg stroke
  (request -> f -> response).class: seg stroke
  (f -> bodyInit).class: direct stroke
  (response -> return).class: seg stroke
  (bodyInit -> return).class: seg stroke
}
