...@envs
direction: right

request.class: square
any.class: square

resolve: {
  class: square
  resolve one: {
    *.class: square
    ctx -> f
  }

  resolve two: {
    *.class: square
    resolve -> ctx -> f
  }
}
request -> resolve.resolve one
request -> resolve.resolve two
resolve.resolve two.f -> any
resolve.resolve one.f -> any
