direction: right

style: {
  fill: transparent
}

vars: {
  d2-config: {
    sketch: true
  }
}

classes: {
  square: {
    style: {
      stroke: purple
      stroke-width: 5
      shadow: true
    }
  }
  seg stroke: {
    style.animated: true
    style.stroke: orange
  }
  direct stroke: {
    style.stroke: "#53C0D8"
  }
}

requests.class: square
petition.class: square
response.class: square

(requests -> petition -> response).class: seg stroke
