direction: right

style: {
  fill: transparent
}

vars: {
  d2-config: {
    sketch: true
  }
}
request: {
  style: {
    stroke: "#53C0D8"
    stroke-width: 5
    shadow: true
  }
}
petition: {
  style: {
    stroke: "#53C0D8"
    stroke-width: 5
    shadow: true
  }
}
response: {
  style: {
    stroke: "#53C0D8"
    stroke-width: 5
    shadow: true
  }
}
request -> petition -> response: {style.animated: true}

