...@envs

request.class: square

request -> petition route.f

petition route: {
  class: square
  f.class: square
  f: |javascript
    // f
    ({query}) =>
      query && query.user
        ? new Response("hello " + query.user , {
            status: 201
        })
        : "not found"
  |
  bodyReponse.class: square
  bodyReponse: |javascript
    Response {
     body: "not found"
     status: 404
    }
  |
  response.class: square
  response: |javascript
    Response {
     body: "hello " + query.user
     status: 201
    }
  |
  headings.class: square
  headings: |javascript
    // headings
    {
     status: 404
    }
  |

  (headings -> f).class: direct stroke
  (f -> bodyReponse).class: seg stroke
  (f -> response).class: seg stroke
  (f -> bodyReponse).class: direct stroke
}

return.class: square

petition route.response -> return
petition route.bodyReponse -> return
