direction: right

...@envs

requests.class: square
petition.class: square
petition2.class: square
response.class: square
response2.class: square
resolve.class: square

(requests -> petition -> response).class: seg stroke
(requests -> petition2 -> response2).class: seg stroke
(resolve -> petition).class: direct stroke
(resolve -> petition2).class: direct stroke
