direction: right

style: {
  fill: transparent
}

vars: {
  d2-config: {
    sketch: true
  }
}
requests: {
  style: {
    stroke: purple
    stroke-width: 5
    shadow: true
  }
  tooltip: Reqests from serve
}
petition: {
  style: {
    stroke: purple
    stroke-width: 5
    shadow: true
  }
}
petition2: {
  style: {
    stroke: purple
    stroke-width: 5
    shadow: true
  }
}
response: {
  style: {
    stroke: purple
    stroke-width: 5
    shadow: true
  }
}
response2: {
  style: {
    stroke: purple
    stroke-width: 5
    shadow: true
  }
}

resolve: {
  style: {
    stroke: purple
    stroke-width: 5
    shadow: true
  }
}
requests -> petition -> response: {
  style.animated: true
  style.stroke: orange
}
requests -> petition2 -> response2: {
  style.animated: true
  style.stroke: orange
}
resolve -> petition: {
  style.stroke: "#53C0D8"
}
resolve -> petition2: {
  style.stroke: "#53C0D8"
}
